import {vector} from '../core';

export const playerSprite = [
  {
    state: 'idle',
    src: 'player/player_idle.png',
    steps: 5,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -7],
  },
  {
    state: 'running',
    src: 'player/player_running.png',
    steps: 6,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -7],
  },
  {
    state: 'falling',
    src: 'player/player_falling.png',
    steps: 1,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -7],
  },
  {
    state: 'jumping',
    src: 'player/player_jumping.png',
    steps: 1,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -7],
  },
];

export const holySprite = [
  {
    state: 'idle',
    src: 'player/holy_idle.png',
    steps: 9,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -8],
  },
  {
    state: 'jumping',
    src: 'player/holy_jumping.png',
    steps: 1,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -8],
  },
  {
    state: 'running',
    src: 'player/holy_running.png',
    steps: 6,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -8],
  },
  {
    state: 'falling',
    src: 'player/holy_falling.png',
    steps: 2,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -8],
  },
];

export const mrManSprite = [
  {
    state: 'idle',
    src: 'player/mrman_idle.png',
    steps: 4,
    current: 1,
    size: vector(16, 16),
    scale: vector(4, 4),
    offset: [-4, -3],
  },
  {
    state: 'jumping',
    src: 'player/mrman_jumping.png',
    steps: 1,
    current: 1,
    size: vector(16, 16),
    scale: vector(4, 4),
    offset: [-4, -3],
  },
  {
    state: 'running',
    src: 'player/mrman_running.png',
    steps: 6,
    current: 1,
    size: vector(16, 16),
    scale: vector(4, 4),
    offset: [-4, -3],
  },
  {
    state: 'falling',
    src: 'player/mrman_falling.png',
    steps: 1,
    current: 1,
    size: vector(16, 16),
    scale: vector(4, 4),
    offset: [-4, -3],
  },
];

export const tommySprite = [
  {
    state: 'idle',
    src: 'player/tommy_idle.png',
    steps: 4,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -7],
  },
  {
    state: 'jumping',
    src: 'player/tommy_jumping.png',
    steps: 1,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -7],
  },
  {
    state: 'running',
    src: 'player/tommy_running.png',
    steps: 8,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -7],
  },
  {
    state: 'falling',
    src: 'player/tommy_falling.png',
    steps: 1,
    current: 1,
    size: vector(32, 32),
    scale: vector(2, 2),
    offset: [-8, -7],
  },
];
